apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-demo-app
  annotations:
    rafay.dev/registry-ko8r76m: registry-rafay-us
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: ci-cd-demo-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ci-cd-demo-app
    spec:
      containers:
        - name: ci-cd-demo-app
          image: registry.rafay.us/ci-cd-demo-app:v1.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
      terminationGracePeriodSeconds: 0
---
apiVersion: v1
kind: Service
metadata:
  name: ci-cd-demo-appe
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
  selector:
    app.kubernetes.io/name: ci-cd-demo-app

