on:
  create:
    branches:
      - "*"
    tags:
      - "v*.*"
    paths:
      - "build/**"
  pull_request:
    branches:
      - "master"
    paths:
      - "build/**"
    types:
      - "closed"
  workflow_dispatch:

env:
  GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
  GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REGISTRY_FQDN: ${{ secrets.REGISTRY_FQDN }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  REPOSITORY_NAME: ${{ secrets.REPOSITORY_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
        
      - name: registry login
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY_FQDN }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}
        
      - name: set tags
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: |
          if [[ ${GITHUB_REF} == refs/heads/* ]]; then
            VERSION=${GITHUB_REF#refs/heads/*}
            [[ ${VERSION} == master ]] && VERSION=latest
          else
            VERSION=${GITHUB_REF#refs/tags/*}
          fi
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
        
      - name: set metadata
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY_FQDN }}/${{ env.REPOSITORY_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=schedule
        
      - name: build and push image
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: docker/build-push-action@v2
        with:
          context: ./build
          file: ./build/Dockerfile
          labels: ${{ steps.metadata.outputs.labels }}
          push: false
          tags: ${{ env.REGISTRY_FQDN }}/${{ env.REPOSITORY_NAME }}:${{ env.VERSION }}
          
      #- name: build and push unprivileged image
      #  if: github.event_name == 'push' || github.even_name == 'workflow_dispatch'
      #  uses: docker/build-push-action@v2
      #  with:
      #    context: ./build
      #    file: ./build/Dockerfile.unprivileged
      #    labels: ${{ steps.metadata.outputs.labels }}
      #    push: false
      #    tags: ${{ env.REGISTRY_FQDN }}/${{ env.REPOSITORY_NAME }}:unprivileged-${{ env.VERSION }}
      
      - name: update deployment manifest
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: |
          cd deploy
          sed -i 's/image:.*/image: ${REGISTRY_FQDN}\/${REPOSITORY_NAME}:${VERSION}/g' deployment.yaml
          #sed -i 's/image:.*/image: ${REGISTRY_FQDN}/${REPOSITORY_NAME}:unprivileged-${VERSION}/g' deployment-unprivileged.yaml
          
          if [ -n $(git status -s) ]; then
            git add -A
            git commit -m "Set container image tag to '${VERSION}'"
            git push origin master
          fi